targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # 仅根据类名自动注册，避免将同文件内的值对象(Params/Statistics等)一并注册
          class_name_pattern: "Service$|Repository$|Provider$|Controller$|UseCase$"
