name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: "90.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate code (injectable)
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Filter coverage (exclude generated/platform files)
        run: |
          python3 scripts/filter_lcov.py
          echo "Filtered coverage at coverage/lcov.filtered.info"

      - name: Enforce coverage threshold (90%)
        run: |
          COVERAGE_THRESHOLD=${{ env.COVERAGE_THRESHOLD }} bash scripts/coverage.sh --filter-only

      - name: Upload coverage artifact (filtered)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.filtered.info

      # 注意：integration_test 通常需要设备/模拟器，默认不在CI执行
      # 可在后续加入 matrix + emulator 配置再启用。
